name: secure_data_app
description: A secure data app with user authentication and secure storage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.3.2
  path_provider: ^2.1.5
  encrypt: ^5.0.3 # For AES Encryption
  local_auth: ^2.3.0
  archive: ^3.3.5
  pointycastle: ^3.7.3
  flutter_local_notifications: ^18.0.1
  introduction_screen: ^3.1.9
  provider: ^6.1.2
  lottie: ^3.3.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  sqflite: ^2.4.1
  open_file: ^3.5.10
  flutter_animate: ^4.5.2
  mime: ^2.0.0
  shared_preferences: ^2.5.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/success.json

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  android: true
  ios: true
